[package]
name = "cotti_terminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textwrap = { version = "0.16.0", features = ["terminal_size"] }
clap = "4.1.1"
termcolor = "1.2.0"
