[package]
name = "c_rust"
version = "0.1.0"
edition = "2021"
links = "out"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
